### ISSUE TITLE
VTT Bridge for Foundry VTT as well

### ISSUE THREAD

**Issue by LAProbert** [averycrespi/vtt-bridge#33]
The request that I have, is would you be able to make a Foundry VTT version of your bridge as well?

https://foundryvtt.com/
It is a new VTT that has some pretty amazing features.
So it would be great to be able to link DMV to it as well.

**Comment by averycrespi** [comment]
I'm willing to add experimental support.

Automatically submitting the commands may be tricky (because of their custom JS event handling), but at the very least I can populate the chatbox with commands.

What does the URL of a normal game look like? I don't have full access, so I've been playing around in the demo at https://foundryvtt.com/demo/game

**Comment by averycrespi** [comment]
Also, looks like the command syntax is Roll20 compatible (or at least the subset that I use), so it should be simple to hook up another DEQUEUE endpoint for commands.

**Comment by averycrespi** [comment]
This feature is being tracked on the `foundry-experimental` branch

**Comment by averycrespi** [comment]
From my experiments, it seems like this is a little of out scope for VTT Bridge. Porting the extension to Foundry would be possible, but Foundry is sufficiently different from Roll20 so that integrating both into the same extension might causes fragility/bloat problems.
